// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type User struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	Email        string
	PasswordHash string
	Name         string
}
